name: CD
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - name: Install npm
        run: 'npm install'
      - name: Build
        run: 'npm run build'
      - name: Firebase configuration
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SECRET_SANTA_EMAIL }}'
          channelId: live
          projectId: secret-santa-email
